qgis_plugin_gpq_downloader.py
Added some logic provide fixes for #8 and #28 
Had a little help from Cursor AI with this one.
=> Added fixes for the filename exported and layer name in QGIS

__init__.py, qgis_plugin_gpq_downloader.py
I think this is a good way to manage the DuckDB dependency. It should install the latest version. #27 
We could probably adapt the init.py to check and make sure it's the correct version as per #34 
Though as that problem arose from using OSGeo4W installer.  
You can check this in the python console using the OSGeo4W installer and hopefully this fix will stop that? #
```
import duckdb
duckdb.sql("PRAGMA version;")
```
=> Added steps to install DuckDB in QGIS at startup

qgis_plugin_gpq_downloader.py
Added in two new layers, from Wherobots and Fused.
=> Added 2 new source layers (ORNL by Wherobots and Fused-partitioned Foursquare)

__init__.py, metadata.txt, qgis_plugin_gpq_downloader.py
Continued on #38 for OS/X
Tweaked the mac install. There's some chance that I didn't need the 3 locations to search, but the first one didn't work and I wanted to try to make it robust.
Also removed the code installing the extensions, as it seemed to be the source of bugs for me.
=> More fixes for DuckDB

qgis_plugin_gpq_downloader.py
Added an 'INSTALL httpfs' to other potential code path
=> make sure httpfs extension gets installed

metadata.txt, qgis_plugin_gpq_downloader.py
* Updated to 2024-12-18.0 release
* Add base -> bathymetry
=> Updated to latest Overture & added bathymetry

metadata.txt, qgis_plugin_gpq_downloader.py
Updated Foursquare links for source coop and hugging face to latest release.
=> fsq link updates, bumped version

qgis_plugin_gpq_downloader.py
=> better protection of column names so geopackage works with fiboa data

__init__.py
Display a message bar while installing DuckDB. Notify the user of success or failure with another message bar.
With regards to QGIS freezing while installing, It seems like this happens even without the message bar being present. When disabling the internet connection, uninstalling DuckDB and then reloading the plugin, QGIS freezes on the current main branch while trying to install. So it appears to me that this is an issue not related to the progress bar. Any takes on this?
Closes #41.
Had a bit of spare time here, hope this helps. Best regards from Heidelberg!
=> Implement message bar for DuckDB installation

__init__.py
Building off of #52 - don't freeze when installing, but run in a worker thread.
This was a much bigger pain than I was expecting, took 2.5+ hours, but looks to be a pretty nice experience now.
=> Do DuckDB installation in a worker thread

README.md, metadata.txt, qgis_plugin_gpq_downloader.py
Just minor changes to the metadata so I can merge improvements to add flatgeobuf.
=> Metadata tweaks on top of PR #59

README.md, metadata.txt, qgis_plugin_gpq_downloader.py
Adds FlatGeobuf support for data downloads.
Closes #12
=> Add FlatGeobuf output support 

qgis_plugin_gpq_downloader.py
Don't just assume bbox name, but check the covering.
Added nhd dataset (which has a different bbox name)
=> Better bbox handling

qgis_plugin_gpq_downloader.py
The button state of the previous execution of the plugin is now saved and loaded to/from QgsSettings. This can probably be done a bit cleaner with some refactoring of the `DataSourceDialog` class, that would again be something for another issue, if wanted.
=> Save state of radio button selection

qgis_plugin_gpq_downloader.py
- Replace Overture dataset selection combo box with checkboxes
- Add support for selecting multiple Overture datasets and base layer subtypes
- Modify URL retrieval and download logic to handle multiple selected datasets
- Implement sequential download queue for multiple datasets
- Improve dialog layout and sizing for new checkbox-based selection
- Resolves #7
=> Ability to select multiple Overture files for download

gpq_downloader/metadata.txt
Fixes #72
One is the heading(in bold), the other some more details (not in bold). These were switched.
=> Switch about and description in metadata.txt

gpq_downloader/data/presets.json
Just updated the urls to make use of the latest.
Closes #74
=> updated overture to february release

gpq_downloader/dialog.py, gpq_downloader/plugin.py
This should hopefully close #99 - the changes for selecting multiple url's in overture seemed to lead to a regression here. Not just on signed url's, but any.
=> Fix bug with custom url's

gpq_downloader/dialog.py, gpq_downloader/utils.py
Closes #89  Enabling layers with no bbox columns to work properly. This one was a pain to fix, took almost an hour, a sneaky little bug.
=> Get geoparquet with no bbox columns working again

.github/workflows/releases.yml, make_release.sh
- New releases workflow will run `make_releases.sh`
- Attaches zip to releases page.
=> added releases workflow

gpq_downloader/data/presets.json
This updates the plugin to Overture's March 2025 release and addresses #115
=> Overture's March 2025 Release

gpq_downloader/utils.py
Changed the way we calculate the bbox for the dataset, due to changes in duckdb 1.3
=> attempted fix for #125

gpq_downloader/metadata.txt
Hopefully we'll now be able to be downloaded into qgis master builds.
=> added max version, per #129
